name: test-build-logic.yml
on:
  push:

jobs:
  test-build-logic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        env:
          BUILD_CACHE_PSW: ${{ secrets.BUILD_CACHE_PSW }}
          BUILD_CACHE_USR: ${{ secrets.BUILD_CACHE_USR }}
        run: ./gradlew build-logic:check
